In [1]:
# ml_w_pytorch_ch16

import torch

sentence = torch.tensor(
    [0,
     7,
     1,
     2,
     5,
     6,
     4,
     3]
)

sentence

tensor([0, 7, 1, 2, 5, 6, 4, 3])

In [14]:
torch.manual_seed(123)
embed = torch.nn.Embedding(10,16)
embedded_sentence = embed(sentence).detach()
embedded_sentence.shape

torch.Size([8, 16])

In [17]:
omega = torch.empty(8,8)

for i, x_i in enumerate(embedded_sentence):
    for j, x_j in enumerate(embedded_sentence):
        omega[i, j] = torch.dot(x_i, x_j)
        
omega.shape

torch.Size([16])

In [51]:
omega_mat = embedded_sentence.matmul(embedded_sentence.T)
omega_mat.shape
(omega.T == omega).all()

tensor(True)

In [22]:
torch.allclose(omega_mat, omega)

True

In [54]:
import torch.nn.functional as F

attention_weights = F.softmax(omega, dim=1)
attention_weights.shape
(attention_weights.T == attention_weights)

tensor([[ True, False, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False],
        [False, False, False,  True, False, False, False, False],
        [False, False, False, False,  True, False, False, False],
        [False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False,  True, False],
        [False, False, False, False, False, False, False,  True]])

In [31]:
attention_weights.sum(dim=1)

tensor([0.9927, 0.9994, 1.0101, 0.9517, 0.9975, 1.0483, 1.0002, 1.0001])

In [45]:
x_2 = embedded_sentence[1, :]
context_vec_2 = torch.zeros(x_2.shape)

for j in range(8):
    x_j = embedded_sentence[j, :]
    context_vec_2 += attention_weights[1, j] * x_j
    
context_vec_2

tensor([-9.3957e-01, -4.6770e-01,  1.0312e+00, -2.8293e-01,  4.9242e-01,
        -1.3848e-02, -2.7449e-01, -7.6353e-01,  1.3956e+00, -9.9441e-01,
        -1.3506e-03,  1.2455e+00, -7.6981e-02,  1.2768e+00, -1.4582e+00,
        -2.1575e+00])