In [11]:
# torch tests

import torch
import math
import torch
import torch.nn as nn
import torch.nn.functional as F

class Example(nn.Module):
    def __init__(self, vocab_size, feature_size):
        super(Example, self).__init__()
        self.embedding = nn.Embedding(vocab_size, feature_size)
        self.layers = nn.TransformerEncoderLayer(d_model=feature_size, nhead=8)
        self.transformer = nn.TransformerEncoder(self.layers, num_layers=6)
        self.decoder = nn.Linear(feature_size, vocab_size)
        
    def forward(self, x):
        # X shape: [seq_len, batch_size]
        print('x.shape initial', x.shape)
        x = self.embedding(x)
        # X shape: [seq_len, batch_size, feature_size]
        print('self.embedding(x)',x.shape)
        x = self.transformer(x)
        # X shape: [seq_len, batch_size, feature_size]
        print('self.transformer(x)', x.shape)
        x = self.decoder(x)
        # X shape: [seq_len, batc_size, vocab_size]
        print('self.decoder(x)', x.shape)
        
        return x
    
model = Example(10, 512)
src = torch.LongTensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]).view(10, 1)
print(src)
# model(src)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [55]:
a = torch.arange(12).view(3,2,2).float()
print('a:\n',a)
a.mean(0, keepdim = True)

a:
 tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]])


tensor([[[4., 5.],
         [6., 7.]]])